### ISSUE TITLE
Hyperlink on projects page redirects to a broken URL

### ISSUE THREAD

**Issue by ThatBryan** [ksxjltze/leejiakeat#1]
![image](https://github.com/ksxjltze/leejiakeat/assets/71874374/b3dab53d-b7fe-4927-a4cf-03a29d3470ac)

**Comment by ksxjltze** [comment]
![image](https://github.com/ksxjltze/leejiakeat/assets/28998429/08912d16-3d8b-48cb-b333-b80fcb0284f2)
fixed..

1. commit 28185cba37b9180cf231015a779a33c64806a35a: fixed broken url
2. commit 070bb603dd5d58c7facb7b48c10a5cb01b9f14d6: fixed failing deployment
